name: deploy

on:
  push:
    branches:
      - master  # Adjust to your branch name

jobs:
  build:
    runs-on: self-hosted  # Self-hosted Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy latest code to /var/www
        run: |
          sudo rsync -av --delete ${{ github.workspace }}/ /var/www/
          cd /var/www

      - name: Install backend
        run: |
          cd /var/www/server
          npm install

      - name: Restart backend in pm2
        run: |
          sudo pm2 restart 0

      - name: Install and build Frontend
        run: |
          cd /var/www/client
          npm install
          npm run build

      - name: Restart nginx
        run: |
          sudo systemctl restart nginx
